//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dealogikal.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtrRecords
    {
        public int recordId { get; set; }
        public string employeeId { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<System.DateTime> timeIn { get; set; }
        public Nullable<System.DateTime> breakOut { get; set; }
        public Nullable<System.DateTime> breakIn { get; set; }
        public Nullable<System.DateTime> timeOut { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public string workMode { get; set; }
    
        public virtual employeeInfo employeeInfo { get; set; }
    }
}
