//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dealogikal.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class images
    {
        public int mediaId { get; set; }
        public string employeeId { get; set; }
        public string imageFile { get; set; }
    
        public virtual employeeInfo employeeInfo { get; set; }
    }
}
