//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dealogikal.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class leaveRequest
    {
        public int requestId { get; set; }
        public string employeeId { get; set; }
        public Nullable<System.DateTime> leaveStart { get; set; }
        public Nullable<System.DateTime> leaveEnd { get; set; }
        public string leaveType { get; set; }
        public string leaveReason { get; set; }
        public System.DateTime dateFiled { get; set; }
        public Nullable<int> status { get; set; }
        public string leaveRequestType { get; set; }
    
        public virtual employeeInfo employeeInfo { get; set; }
    }
}
