//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dealogikal.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class loginLogs
    {
        public int logId { get; set; }
        public string employeeId { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public string ipaddress { get; set; }
        public string addresslink { get; set; }
    
        public virtual employeeInfo employeeInfo { get; set; }
    }
}
