//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dealogikal.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DealogikalDTREntities : DbContext
    {
        public DealogikalDTREntities()
            : base("name=DealogikalDTREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<accLogs> accLogs { get; set; }
        public virtual DbSet<dtrRecords> dtrRecords { get; set; }
        public virtual DbSet<employeeInfo> employeeInfo { get; set; }
        public virtual DbSet<feedback> feedback { get; set; }
        public virtual DbSet<images> images { get; set; }
        public virtual DbSet<leaveRequest> leaveRequest { get; set; }
        public virtual DbSet<loginLogs> loginLogs { get; set; }
        public virtual DbSet<notification> notification { get; set; }
        public virtual DbSet<obRequest> obRequest { get; set; }
        public virtual DbSet<overtimeRequest> overtimeRequest { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<todoLists> todoLists { get; set; }
        public virtual DbSet<userAccount> userAccount { get; set; }
        public virtual DbSet<vw_Role> vw_Role { get; set; }
    }
}
