//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dealogikal.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class obRequest
    {
        public int obId { get; set; }
        public string employeeId { get; set; }
        public System.DateTime dateFiled { get; set; }
        public System.DateTime obDate { get; set; }
        public System.DateTime startTime { get; set; }
        public System.DateTime endTime { get; set; }
        public int status { get; set; }
    
        public virtual employeeInfo employeeInfo { get; set; }
    }
}
