//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dealogikal.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class todoLists
    {
        public int contentId { get; set; }
        public string employeeId { get; set; }
        public string contents { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
    
        public virtual employeeInfo employeeInfo { get; set; }
    }
}
